version: '3.8'

services:
  bot:
    container_name: bot
    image: metravod/weather_bot:0.0.1
  db:
    container_name: db
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:14.5